### ISSUE TITLE
rename repository to ensure naming conventions

### ISSUE THREAD

**Issue by danduk82** [geoadmin/tool-batch-tippecanoe#1]
hi @swissmap , could you please rename the repository to follow the conventions described [here](https://github.com/geoadmin/doc-guidelines/blob/master/NAMES.md)

I propose to prepend `tool-` so that the repository becomes `tool-batch-tippecanoe`

**Comment by swissmap** [comment]
@danduk82 : repository was created by marc in my name and now seems to be corrected (by somebody else?).
I also changed the wrong spelled readme.md filename.
